# Generated by Django 4.1.5 on 2023-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
