# Generated by Django 4.1.5 on 2023-01-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ipaddressmodel_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='ip_combinations',
            field=models.TextField(blank=True, null=True, verbose_name='Combinaciones'),
        ),
    ]
